CREATE DATABASE RentVehicles;
  GO
 
  USE RentVehicles;
  GO
 
  CREATE TABLE Vehicles (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Brand NVARCHAR(50) NOT NULL,
  Model NVARCHAR(50) NOT NULL,
  VehicleYear INT NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  CurrentStatus NVARCHAR(20) NOT NULL,
  Photo NVARCHAR(100) NOT NULL
  );
 
  CREATE TABLE Customers (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FirstName NVARCHAR(100) NOT NULL,
  LastName NVARCHAR(100) NOT NULL,
  Phone NVARCHAR(15) NOT NULL,
  Email NVARCHAR(100) UNIQUE NOT NULL
  );
 
  CREATE TABLE Employees (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FirstName NVARCHAR(100) NOT NULL,
  LastName NVARCHAR(100) NOT NULL,
  Position NVARCHAR(50) NOT NULL,
  Phone NVARCHAR(15) NOT NULL,
  Email NVARCHAR(100) UNIQUE NOT NULL
  );
 
  CREATE TABLE Bookings (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  CustomerId INT FOREIGN KEY REFERENCES Customers(Id) ON DELETE CASCADE,
  VehicleId INT FOREIGN KEY REFERENCES Vehicles(Id) ON DELETE CASCADE,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  BookingStatus NVARCHAR(20) NOT NULL
  );
 
  CREATE TABLE Payments (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  BookingId INT FOREIGN KEY REFERENCES Bookings(Id) ON DELETE CASCADE,
  Amount DECIMAL(10,2) NOT NULL,
  PaymentMethod NVARCHAR(50) NOT NULL,
  PaymentDate DATE NOT NULL
  );
 
  CREATE TABLE Insurance (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  BookingId INT FOREIGN KEY REFERENCES Bookings(Id) ON DELETE CASCADE,
  SecureType NVARCHAR(50) NOT NULL,
  Amount DECIMAL(10,2) NOT NULL
 );
ALTER TABLE Employees
ADD Password NVARCHAR(255) NOT NULL;